language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --dev --no-interaction --prefer-source --no-suggest

script:
  - vendor/bin/phpunit
